### ISSUE TITLE
PR on PHP 7.1 support

### ISSUE THREAD

**Issue by ywarnier** [szymach/c-pchart#25]
Hi,

We still use pChart and we'd like it to support PHP 7.1 (it is currently broken). In the eventuality that we would continue using it an maintain it, would you accept PRs, or would you prefer us to fork it and maintain it apart from you?

**Comment by ywarnier** [comment]
The question still stands, but I realized I didn't have the latest version, which apparently supports 7.1

**Comment by szymach** [comment]
Hello, 
Yes, I still maintain the repository, although no longer add new features. If you would like to submit changes or fixes I will be happy to review them :)

**Comment by szymach** [comment]
I assume the matter is resolved, yes?

**Comment by ywarnier** [comment]
Indeed. Thanks!

**Comment by kmchen13** [comment]
Hello,
May I know whitch version is talken about. I downloaded pChart 2.1.4 at http://www.pchart.net/download and it still be broken with php 7.1

**Comment by szymach** [comment]
That is because I do not own that code, this is a separate library that is built on top of the one from your link.

If you want to use my code, follow the instructions in the README.

**Comment by kmchen13** [comment]
Should I understand that your code is a continuation of pChart 2.1.4 ?
Where can it be downloaded ?

**Comment by szymach** [comment]
It is not really a continuation, since I do not actively develop it, just maintain it for people who still use it. It was adjusted to be able to run on newer versions of PHP, with some minor fixes and features mostly contributed by other people. You can install it via Composer (see [here](https://github.com/szymach/c-pchart#installation-via-composer)) or you can download a ZIP file from Github, although you will need to handle class autoloading on your own then.
