### ISSUE TITLE
Remove the rest of ImageMapper ?

### ISSUE THREAD

**Issue by bozhinov** [szymach/c-pchart#54]
Since all the JavaScript is gone there is no point in keeping the ImageMap functions

**Comment by szymach** [comment]
Well since you have said that the sandbox is a feature that is actively being used, perhaps it would simply be better to reintroduce it along with the javascripts? It would probably require me to do some code updates to the sandbox files (have not really looked at them), but we can go in that direction.

**Comment by bozhinov** [comment]
I haven't gotten that far yet, as the JS needs major refactoring as well
I have also chosen to go with jQuery for my fork
